l1=[1,2,3,4,5] 
print("List: ",l1)
print("Sum: ",sum(l1))
print("Minimum value: ",min(l1))
print("Maximum value: ",max(l1))
l1.sort()
print("Ascending: ",l1)
l1.reverse()
print("Descending: ",l1)
l2=(l1)                
print("Tuple: ",l1)
del(l2)
print(l2)